import { inter, poppins } from './fonts'
import { Metadata } from 'next'
import '@/styles/globals.css'
import { SessionProvider } from '@/providers/SessionProvider'
import { Toaster } from '@/components/ui/sonner'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable}`}>
        <Toaster />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  )
}
